### ISSUE TITLE
.11 release checklist

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#262]
- [ ] Test ladder games
- [x] Test client updating from 0.10.125
- Test custom games with all featured mods:
 - [ ] Beta
 - [x] 3650
 - [ ] Blackops
 - [ ] Civ def.
 - [ ] Claustrophobia
 - [ ] Diamond
 - [ ] King of the Hill
 - [ ] LABWars
 - [ ] Murder Party
 - [ ] Nomads
 - [ ] Phantom-X
 - [ ] Vanilla
 - [ ] Wyvern
 - [ ] Xtreme Wars
- [x] Test game updating
- [x] Test map/mod download from vault
- [ ] Test replays
- [x] Test leaderboards

**Comment by Sheeo** [comment]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=11133&p=114322#p114304

**Comment by Sheeo** [comment]
hovering over a game in "find games" doesn't show the list of players in the game
